books = [{
        'asin': '1511365056',
        'title': "The Empire's Ruin",
        'subtitle': 'Ashes of the Unhewn Throne, Book 1',
        'authors': 'Brian Staveley',
        'narrators': 'Moira Quirk, Joe Jameson, Oliver Cudbill',
        'series_title': 'Ashes of the Unhewn Throne',
        'series_sequence': '1',
        'genres': 'Science Fiction & Fantasy, Fantasy, Epic, Science Fiction & Fantasy, Fantasy, Military',
        'runtime_length_min': '2133',
        'is_finished': 'True',
        'percent_complete': '0.0',
        'rating': '-',
        'num_ratings': '-',
        'date_added': "2021-10-31T04':00':01.111Z",
        'release_date': '2021-07-06',
        'cover_url': "https'://m.media-amazon.com/images/I/5111PZnNaTS._SL500_.jpg",
        'description': '<p>The Annurian Empire is disintegrating. The advantages it used for millennia have fallen to ruin. The ranks of the Kettral have been decimated from within, and the kenta gates, granting instantaneous travel across the vast lands of the empire, can no longer be used. In order to save the empire, one of the surviving Kettral must voyage beyond the edge of the known world through a land that warps and poisons all living things to find the nesting ground of the giant war hawks. Meanwhile, a monk turned con-artist may hold the secret to the kenta gates.</p>',
    }, {
        'asin': '1529050278',
        'title': 'Empire in Black and Gold',
        'subtitle': 'Shadows of the Apt, Book 1',
        'authors': 'Adrian Tchaikovsky',
        'narrators': 'Ben Allen',
        'series_title': 'Shadows of the Apt',
        'series_sequence': '1',
        'genres': 'Science Fiction & Fantasy, Fantasy, Action & Adventure, Science Fiction & Fantasy, Fantasy, Epic, Science Fiction & Fantasy, Fantasy, Paranormal & Urban, Contemporary',
        'runtime_length_min': '1384',
        'is_finished': 'False',
        'percent_complete': '0.0',
        'rating': '-',
        'num_ratings': '-',
        'date_added': "2021-10-31T04':00':01.111Z",
        'release_date': '2020-12-10',
        'cover_url': "https'://m.media-amazon.com/images/I/515oMLa6E1L._SL500_.jpg",
        'description': '<p>The Lowlands’ city states have lived in peace for decades, hailed as bastions of civilization. Yet that peace is about to end. A distant empire has been conquering neighbours with highly trained soldiers and sophisticated combat techniques. And the city states are its desirable new prize. Only the ageing Stenwold Maker – spymaster, artificer and statesman – foresees the threat, as the empires’ armies march ever closer. So it falls upon his shoulders to open the eyes of the cities’ leaders.</p>',
    }, {
        'asin': '154591818X',
        'title': 'Mere Apologetics',
        'subtitle': 'How to Help Seekers and Skeptics Find Faith',
        'authors': 'Alister E. McGrath',
        'narrators': 'Shaun Grindell',
        'series_title': '',
        'series_sequence': '',
        'genres': 'Religion & Spirituality, Christianity, Theology, Apologetics',
        'runtime_length_min': '384',
        'is_finished': 'False',
        'percent_complete': '43.49',
        'rating': '-',
        'num_ratings': '-',
        'date_added': "2021-10-03T15':59':18.526Z",
        'release_date': '2021-04-13',
        'cover_url': "https'://m.media-amazon.com/images/I/51zOO9PjZ-L._SL500_.jpg",
        'description': "<p>Throughout history there have been great and articulate defenders of the faith, from Augustine and Aquinas to Jonathan Edwards, G. K. Chesterton, Francis Schaeffer, and C. S. Lewis. But with new challenges comes the need for a fresh apologetic that specifically addresses the arguments levied against faith in our time of scientific atheism and skepticism. Alister McGrath's <i>Mere Apologetics</i> seeks to equip listeners to engage gracefully and intelligently with the challenges facing the faith today while drawing appropriately on the wisdom of the past. </p>",
    }, {
        'asin': '1549119044',
        'title': 'The Hundred Thousand Kingdoms',
        'subtitle': '',
        'authors': 'N. K. Jemisin',
        'narrators': 'Casaundra Freeman',
        'series_title': 'The Inheritance Trilogy',
        'series_sequence': '1',
        'genres': 'Science Fiction & Fantasy, Fantasy, Action & Adventure, Science Fiction & Fantasy, Fantasy, Epic',
        'runtime_length_min': '707',
        'is_finished': 'True',
        'percent_complete': '0.0',
        'rating': '-',
        'num_ratings': '-',
        'date_added': "2021-09-06T08':16':42.705Z",
        'release_date': '2018-10-16',
        'cover_url': "https'://m.media-amazon.com/images/I/51LP8KXrFQL._SL500_.jpg",
        'description': "<p>Yeine Darr is an outcast from the barbarian North. But when her mother dies under mysterious circumstances, she is summoned to the majestic city of Sky. There, to her shock, Yeine is named an heiress to the king. But the throne of the Hundred Thousand Kingdoms is not easily won, and Yeine is thrust into a vicious power struggle with cousins she never knew she had. As she fights for her life, she draws ever closer to the secrets of her mother's death and her family's bloody history. </p>",
    }, {
        'asin': '1705034039',
        'title': 'Thank You for Rejecting Me',
        'subtitle': 'Transform Pain into Purpose and Learn to Fight for Yourself',
        'authors': 'Kait Warman',
        'narrators': 'Kait Warman',
        'series_title': '',
        'series_sequence': '',
        'genres': "Religion & Spirituality, Christianity, Christian Living, Marriage & Relationships, Religion & Spirituality, Christianity, Christian Living, Spiritual Growth, Religion & Spirituality, Christianity, Christian Living, Women's Christian Living",
        'runtime_length_min': '390',
        'is_finished': 'True',
        'percent_complete': '0.0',
        'rating': '-',
        'num_ratings': '-',
        'date_added': "2021-09-13T00':30':55.802Z",
        'release_date': '2021-02-16',
        'cover_url': "https'://m.media-amazon.com/images/I/512nEd0yCxL._SL500_.jpg",
        'description': '<p>Rejection comes in many forms, but it does not have to debilitate you. A popular relationship coach and podcaster helps you overcome rejection with practical strategies to get back on your feet, grow in grit and confidence, and live unflinchingly. </p>asin=',
    }]
