__author__ = "snowskeleton"
__author_email__ = "isaac@snowskeleton.net"
__description__ = "RSRSSB builds an RSS feed with arbitrary audio files."
__license__ = "Apache 2.0"
__status__ = "Development"
__title__ = "rsrssb"
__url__ = "https://github.com/snowskeleton/rsrssb"
__version__ = "0.2.0-0"
